### PR TITLE
delete trailing line feed code

### PR DESCRIPTION
**Pull request by nabewata07**
delete trailing line feed code to avoid an error of basic authentication

### CODE REVIEW

**Comment by kanet77** [comment]
Thanks for the PR.
Can you help me understand why the `chomp` is needed? I would expect any user input to be cleaned before being passed to togglv8.
If `chomp` is actually needed on `username`, why is it not also needed on `password`?

**Comment by nabewata07** [comment]
@kanet77 
Sorry for less information.

https://github.com/kanet77/togglv8#initialization
When the file `.toggl` is used for API token, the token come into the `username` value with line feed code and authentication will fail.
If `.toggl` file is supported, `chomp` is needed for `username`.

thank you.

**Comment by kanet77** [comment]
I see now. Sorry I didn't get back to you sooner.

That seems like a reasonable improvement. Can you add a test to this PR? I'll try to be more responsive.

**Comment by nabewata07** [comment]
Sorry, I found 
https://github.com/kanet77/togglv8/pull/21
is same idea.
The PR has been merged. Sorry for my confusing you.
I close this PR, thank you for your kindness.

**Comment by kanet77** [comment]
I'm glad you found that. Sorry that I didn't find the time to give you a more detailed response. I had forgotten some of the details. Thanks for the PR!

**Pull request closed without merging**
