### PR TITLE
allow access to workspace tags and update unsupported str hash syntax

### PR DESCRIPTION
**Pull request by dylanlewis89**
Creating new get request that gives access to a workspace's tags. Also, cleaning up old hash syntax that was breaking tests.

### CODE REVIEW

**Comment by dylanlewis89** [comment]
Hi @kanet77 -- do you have an estimate of when you'll be able to take a look at this PR? Thanks!

**Comment by kanet77** [comment]
I'll take a look tonight.

**Comment by kanet77** [comment]
Thanks for adding this functionality and the test!

To clarify, are you referring to `{ symbol: 'value' }` as "old hash syntax"? That was introduced in Ruby 1.9 whereas `{ :symbol => 'value' }` is the original syntax.

Out of curiosity, what was the error for breaking tests? The tests pass locally and in Travis CI using the `params = { 'active': false }` syntax. It's a moot point because I just pushed [v1.0.5](https://github.com/kanet77/togglv8/releases/tag/v1.0.5) that switches to using => (hashrocket) in all hashes.

**Comment by dylanlewis89** [comment]
Awesome - thanks @kanet77!

I forget exactly which test the syntax was breaking but running rspec on the whole project failed for me. May have been the version of ruby I was using. As I recall, it was specifically a problem with the `{ "string": 'value' }` syntax.

Thanks for creating this project -- I've enjoyed working with it thus far, so you may see more PRs coming soon :)

**Comment by kanet77** [comment]
Aha! Did you get this error?

    SyntaxError: (irb):4: syntax error, unexpected ':', expecting =>

The `{ 'symbol': 'value' }` syntax was introduced in Ruby 2.2. The key shown here is a symbol although it looks like a string. The purpose for the quotes is to allow symbols with special characters. (http://stackoverflow.com/a/27759858)

The line you changed was clearly a typo or a copy/paste error and it was the only hash with that syntax.

Glad to hear this project is valuable to you. I released the [v1.1.0 gem](https://rubygems.org/gems/togglv8/versions/1.1.0).

**Comment by dylanlewis89** [comment]
Yup, totally was the error I was getting. Thanks!

**Pull request merged**
