### PR TITLE
Reports API Support

### PR DESCRIPTION
**Pull request by worldsmithroy**
This pull-request adds support for the Toggl Reports v2 API, and plays nicely with the latest version of the codebase.

### CODE REVIEW

**Comment by worldsmithroy** [comment]
The specs fail for me even in the togglv8/master HEAD, so it doesn't look like these are tied with my changes.

Having said that, I'm looking into the source, and may need to open an issue, because I can tell that they are working on other pull-requests.

**Comment by kanet77** [comment]
Thanks for the PR! I am traveling till November.  Will review as soon as I can after returning.

**Comment by blackjid** [comment]
Are there any plans to rebase and merge this??? I could use it :)

**Comment by blackjid** [comment]
I've rebased it in https://github.com/platanus/togglv8/tree/worldsmithroy-reports

**Comment by kanet77** [comment]
Thanks @worldsmithroy for your work on the Reports API. I listed you as a contributor and added a link to your fork on my README.

When I added support I started from scratch and added tests as I went. In retrospect we could have worked together on this PR. I'm disappointed that I didn't have the time till now to take care of it. I no longer use Toggl or write Ruby code and this project was put on the back burner.

My hope is that this library is nearly complete now and any incoming changes will be fairly minor. If you have any changes to recommend, I will be more responsive.

Cheers!

**Pull request closed without merging**
